### ISSUE TITLE
Influxdb build error when performing "Build and run IOT Edge Solution in Simulator " 

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [Azure-Samples/iot-edge-influxdb-grafana#1]
Env:  Ubuntu on WSL 

ERROR: for influxdb  Cannot create container for service influxdb: invalid mount config for type "bind": bindCreating grafana      ... done

ERROR: for influxdb  Cannot create container for service influxdb: invalid mount config for type "bind": bind source path does not exist: /srv/influx
ERROR: Encountered errors while bringing up the project.
ERROR: Error while executing command: docker-compose -f /var/lib/iotedgehubdev/data/docker-compose.yml up. Command '['docker-compose', '-f', '/var/lib/iotedgehubdev/data/docker-compose.yml', 'up']' returned non-zero exit status 1.

**Comment by idavis** [comment]
I believe you need to create the `/srv/influx` folder or have it point to another location that exists. [This article](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-access-host-storage-from-module) also talks about setting up the correct ownership and permissions for external mounts.

**Comment by MagdaPaj** [comment]
I'm unable to make the sample work due to the same error. If you prefer I can create a separate issue for it.

My setup:
- Visual Studio Code
- Docker Desktop WSL 2 backend

I created a folder and I specified it in the .env file like this: 
`INFLUX_BIND="C:\\Users\\foo\\repos\\github\\iot-edge-influxdb-grafana\\storageInflux:/var/lib/influxdb"`

Then the generated part for influxdb in the deployment file looks like this
```          
          "influxdb": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "localhost:5000/influxdb:1.7.1-amd64",
              "createOptions": "{\"Hostname\":\"influxdb\",\"Env\":[\"INFLUX_DATABASE=inference\",\"INLFUX_ADMIN_USER=${INFLUX_ADMIN_USER}\",\"INFLUX_ADMIN_PASS=grafana\"],\"HostConfig\":{\"Binds\":[\"C:\\\\Users\\\\foo\\\\repos\\\\github\\\\iot-edge-influxdb-grafana\\\\storageInflux:/var/lib/influxdb\"],\"PortBindings\":{\"8086/tcp\":[{\"HostPort\":\"8086\"}]}}}"
            }
          },
```

And the Build and run IoT Edge Solution is stuck on this step:
```
edgeHub image version is ignored in solution mode.
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
Network azure-iot-edge-dev is external, skipping
```
It doesn't fail, it doesn't finish. There are no more logs, errors. I'm not really sure what's the problem. And none of the container influxdb, grafana, simulator, orchestrator is started. 

I've also tried to specify `createOptions` with JSON (instead of specifying it as string), like this:
```
              "createOptions": {
                "Hostname": "influxdb",
                "Env": [
                  "INFLUX_DATABASE=inference",
                  "INLFUX_ADMIN_USER=grafana",
                  "INFLUX_ADMIN_PASS=grafana"
                ],
                "HostConfig": {
                  "Binds": [
                    "C:\\Users\\foo\\repos\\github\\iot-edge-influxdb-grafana\\storageInflux:/var/lib/influxdb"
                  ],
                  "PortBindings": {
                    "8086/tcp": [
                      {
                        "HostPort": "8086"
                      }
                    ]
                  }
                }
              }
```
However, it's not accepted.

Am I doing something incorrectly, or the sample is not supposed to work on my setup?
